// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8zm9nb8jk2edL1Apt1wsYSw909hsMfHU',
    appId: '1:1091887851393:android:eb2bfc98efe38422e16a80',
    messagingSenderId: '1091887851393',
    projectId: 'pushnotification-91b2a',
    storageBucket: 'pushnotification-91b2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8j9stkfZy7a4WLi_ISIM99quqxolK2uk',
    appId: '1:1091887851393:ios:8d03375e61947217e16a80',
    messagingSenderId: '1091887851393',
    projectId: 'pushnotification-91b2a',
    storageBucket: 'pushnotification-91b2a.appspot.com',
    iosClientId: '1091887851393-begquf7ukfvhalhs2kmpio5gtc72a1pe.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushnotifications',
  );
}
